name: Assign Domain
# This workflow is triggered on pushes to the repository.
on:
  push:
    branches:
    - source

jobs:
  createFile:
    name: Assing domain
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: 1arp/create-a-file-action@0.2
        with:
          path: 'src'
          file: 'foo.bar'
          content: |
            Hello
            World